# Generated by Django 4.2.17 on 2026-01-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(default="Asia/Seoul", max_length=50),
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "db_table": "time_slots",
                "ordering": ["start_datetime"],
                "unique_together": {("event", "start_datetime")},
            },
        ),
    ]
