# Generated by Django 4.2.17 on 2026-01-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_date_end_event_date_start_event_deadline_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
