# Generated by Django 4.2.17 on 2026-01-07 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0004_event_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chosen_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chosen_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_choice",
                        to="events.event",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_choices",
                        to="events.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Final Choice",
                "verbose_name_plural": "Final Choices",
                "db_table": "final_choices",
                "ordering": ["-created_at"],
            },
        ),
    ]
