# Generated by Django 4.2.17 on 2026-01-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="익명", max_length=50),
        ),
    ]
