# Generated by Django 4.2.17 on 2026-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
