# Generated by Django 4.2.17 on 2026-01-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_date_end_event_date_start_event_deadline_at_and_more"),
        ("participants", "0002_participant_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="participants.participant",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="events.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Availability",
                "verbose_name_plural": "Participant Availabilities",
                "db_table": "participant_availabilities",
                "ordering": ["time_slot__start_datetime"],
                "unique_together": {("participant", "time_slot")},
            },
        ),
    ]
