# Generated by Django 4.2.17 on 2026-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_participantavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="전화번호 (알림톡 발송용)",
                max_length=20,
                null=True,
            ),
        ),
    ]
